### ISSUE TITLE
Data Raceが発生する

### ISSUE THREAD

**Issue by Nagarei** [isucon/isucandar#8]
おそらく #3 と同じ問題(チャンネルに書き込み中にcloseされる場合がある)がscore.goにもあります。
ベンチマーカー内のAddScoreを実行するルーチンがcontext無視してると起こる。
https://github.com/isucon/isucandar/blob/ee64d078503513fd98bded1f67b7262b429af5a4/score/score.go#L74
https://github.com/isucon/isucandar/blob/ee64d078503513fd98bded1f67b7262b429af5a4/score/score.go#L82

**Comment by rosylilly** [comment]
fixed by 929eaae2f9cb52185c958a8058f1b7391277acec
